export const data = {
  firstName: "Sobuj",
  middleName: "Vai",
  lastName: "Developer",
  suffix: ["I", "II", "III", "IV", "V", "Jr.", "Sr."],
  dateOfBirth: {
    day: 23,
    month: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "Auguest",
      "September",
      "October",
      "November",
      "December",
    ],
    year: 2000,
  },
  ssn: {
    value: "77777",
    isSsn: true,
  },
  isHomeless: false,
  address: {
    street: "Ghior",
    zip: "10008",
    city: "dhaka",
  },
  isAlsoMailing: true,
  mailingAddress: {
    street: "Ghior",
    zip: "10008",
    city: "dhaka",
  },
  phoneNumber: "018XXXXXXXX",
  emailAddress: "coder@gmail.com",
};
